### ISSUE TITLE
Synapse OIDC fails with error code "invalid_token"

### ISSUE THREAD

**Issue by etkecc** [H2CK/oidc#5]
Hi there,

I'm trying to use this project as identity provider for [matrix-org/synapse](https://github.com/matrix-org/synapse), but faced an unexpected error.

The error text:

```
 invalid_use: Key "use" is not valid for your usage 
```

The error code:

```
invalid_token
```

The error log:

```
synapse.handlers.oidc - 843 - ERROR - GET-43 - Invalid id_token
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/synapse/handlers/oidc.py", line 840, in handle_oidc_callback
    id_token = await self._parse_id_token(token, nonce=session_data.nonce)
  File "/usr/local/lib/python3.9/site-packages/synapse/handlers/oidc.py", line 698, in _parse_id_token
    claims = jwt.decode(
  File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7519/jwt.py", line 99, in decode
    data = self._jws.deserialize_compact(s, load_key, decode_payload)
  File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7515/jws.py", line 103, in deserialize_compact
    if algorithm.verify(signing_input, signature, key):
  File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7518/_cryptography_backends/_jws.py", line 48, in verify
    op_key = key.get_op_key('verify')
  File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7517/models.py", line 44, in get_op_key
    self.check_key_op(operation)
  File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7517/models.py", line 75, in check_key_op
    raise InvalidUseError()
authlib.jose.errors.InvalidUseError: invalid_use: Key "use" is not valid for your usage
```

The synapse OIDC config:

```yaml
  oidc_providers:
  - idp_id: nextcloud
    idp_name: NextCloud
    idp_brand: "nextcloud"
    discover: no
    issuer: "https://REDACTED"
    client_id: "REDACTED"
    client_secret: "REDACTED"
    authorization_endpoint: https://REDACTED/index.php/apps/oidc/authorize
    token_endpoint: https://REDACTED/index.php/apps/oidc/token
    userinfo_endpoint: https://REDACTED/index.php/apps/oidc/userinfo
    jwks_uri: https://REDACTED/index.php/apps/oidc/jwks
    client_auth_method: client_secret_post
    scopes: ["openid", "profile"]
    user_mapping_provider:
      config:
        localpart_template: "{{ user.sub|lower }}"
        display_name_template: "{{ user.name }}"
```

Synapse uses [authlib](https://github.com/lepture/authlib) to handle OIDC/OAuth2.

Could you help to fix that issue, please?

**Comment by H2CK** [comment]
According to the error message I would expect that Synapse wants to retrieve a key that could also be used for encryption. (For now I am not sure why)
The current implementation of the oidc app only provides the key usage as use=[sig] and keyOps=[verify], since the key is only used for signing the JWT Token.

I will have a look at the OpenID Connect Specification and check if there is some misinterpretation here.

**Comment by etkecc** [comment]
Thank you!

Please note that synapse doesn't implement OIDC itself, but uses the [authlib](https://github.com/lepture/authlib)

**Comment by H2CK** [comment]
The use attribute of the JWK endpoint was not set compliant to the OpenID Connect specification.
The problem should be solved with version 0.1.2 of oidc app.
Please try if this solves your problem. If not please give feedback here.

**Comment by etkecc** [comment]
Thank you!
It will take some time to deploy and test new version

**Comment by etkecc** [comment]
Tested it.
Unfortunately, the version 0.1.2 has exactly the same problem, so it's not fixed

**Comment by etkecc** [comment]
Ignore previous comment - it works!
I don't know why it didn't work right after update, but may be some cache.

Thank you for fix!
